# DigitalOcean App Platform Specification
# Deploy using: doctl apps create --spec app.yaml

name: mess-management

services:
  - name: web
    # Source configuration - update with your repo
    github:
      repo: Wahla-007/Suf-Proj
      branch: main
      deploy_on_push: true
    
    # Build using Dockerfile
    dockerfile_path: Dockerfile
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # Smallest instance ($5/month)
    
    # HTTP configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080

    # Routes
    routes:
      - path: /

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
