// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mess_management.Models;

#nullable disable

namespace mess_management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219130141_AddUserFields")]
    partial class AddUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mess_management.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPasswordChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__AspNetUs__3213E83F6A26BF7E");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("mess_management.Models.MonthlyBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FoodAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("GeneratedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('now()')");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("PreviousDue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalDue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("TotalMeals")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaterShare")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MonthlyB__3213E83F2AF691CE");

                    b.HasIndex("TeacherId");

                    b.ToTable("MonthlyBill", (string)null);
                });

            modelBuilder.Entity("mess_management.Models.TeacherAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Breakfast")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<bool?>("Dinner")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("Lunch")
                        .HasColumnType("bit");

                    b.Property<string>("MarkedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("System");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VerificationNote")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__TeacherA__3213E83FF8935387");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAttendance", (string)null);
                });

            modelBuilder.Entity("mess_management.Models.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BreakfastRate")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DinnerRate")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("LunchRate")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__WeeklyMe__3213E83F7983D1E9");

                    b.HasIndex("CreatedById");

                    b.ToTable("WeeklyMenu", (string)null);
                });

            modelBuilder.Entity("mess_management.Models.MonthlyBill", b =>
                {
                    b.HasOne("mess_management.Models.AspNetUser", "Teacher")
                        .WithMany("MonthlyBills")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__MonthlyBi__Teach__412EB0B6");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("mess_management.Models.TeacherAttendance", b =>
                {
                    b.HasOne("mess_management.Models.AspNetUser", "Teacher")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__TeacherAt__Teach__4222D4EF");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("mess_management.Models.WeeklyMenu", b =>
                {
                    b.HasOne("mess_management.Models.AspNetUser", "CreatedBy")
                        .WithMany("WeeklyMenus")
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("FK__WeeklyMen__Creat__4316F928");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("mess_management.Models.AspNetUser", b =>
                {
                    b.Navigation("MonthlyBills");

                    b.Navigation("TeacherAttendances");

                    b.Navigation("WeeklyMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
